"""empty message

Revision ID: 253b87f32080
Revises: 
Create Date: 2024-05-01 12:21:19.652732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253b87f32080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
